// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package oaas

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	// Types that are valid to be assigned to Type:
	//	*Data_Raw
	//	*Data_Final
	Type                 isData_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_db932517fbf53ff2, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

type isData_Type interface {
	isData_Type()
}

type Data_Raw struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3,oneof"`
}
type Data_Final struct {
	Final string `protobuf:"bytes,2,opt,name=final,oneof"`
}

func (*Data_Raw) isData_Type()   {}
func (*Data_Final) isData_Type() {}

func (m *Data) GetType() isData_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Data) GetRaw() []byte {
	if x, ok := m.GetType().(*Data_Raw); ok {
		return x.Raw
	}
	return nil
}

func (m *Data) GetFinal() string {
	if x, ok := m.GetType().(*Data_Final); ok {
		return x.Final
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Data) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Data_OneofMarshaler, _Data_OneofUnmarshaler, _Data_OneofSizer, []interface{}{
		(*Data_Raw)(nil),
		(*Data_Final)(nil),
	}
}

func _Data_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Data)
	// type
	switch x := m.Type.(type) {
	case *Data_Raw:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Raw)
	case *Data_Final:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Final)
	case nil:
	default:
		return fmt.Errorf("Data.Type has unexpected type %T", x)
	}
	return nil
}

func _Data_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Data)
	switch tag {
	case 1: // type.raw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Type = &Data_Raw{x}
		return true, err
	case 2: // type.final
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Data_Final{x}
		return true, err
	default:
		return false, nil
	}
}

func _Data_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Data)
	// type
	switch x := m.Type.(type) {
	case *Data_Raw:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Raw)))
		n += len(x.Raw)
	case *Data_Final:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Final)))
		n += len(x.Final)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Data)(nil), "oaas.Data")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_db932517fbf53ff2) }

var fileDescriptor_data_db932517fbf53ff2 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4f, 0x4c, 0x2c, 0x56, 0xb2, 0xe2, 0x62,
	0x71, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe2, 0x62, 0x2e, 0x4a, 0x2c, 0x97, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0xf1, 0x60, 0x08, 0x02, 0x71, 0x84, 0xc4, 0xb8, 0x58, 0xd3, 0x32, 0xf3, 0x12, 0x73, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x3d, 0x18, 0x82, 0x20, 0x5c, 0x27, 0x36, 0x2e, 0x96, 0x92, 0xca,
	0x82, 0xd4, 0x24, 0x36, 0xb0, 0x41, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x34, 0xbf,
	0x93, 0x56, 0x00, 0x00, 0x00,
}
